/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.halfangel.rpc.properties;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class thrift_datatypeConstants {

  public static final java.lang.String VERSION = "1.0.1";

}
